name: Repository Dispatch
on:
  repository_dispatch:
    types: [my-event]
jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: mask
        id: mask
        shell: bash
        run: |
          cluster_conf_encoded=$(jq -r '.client_payload.cluster_conf_encoded' $GITHUB_EVENT_PATH)
          echo "::add-mask::$cluster_conf_encoded"
      - name: Decode cluster.conf
        run: |
          echo "${{ github.event.client_payload.cluster_conf_encoded }}" | base64 -d >> cluster.conf
          cat cluster.conf
