name: Repository Dispatch
on:
  repository_dispatch:
    types: [my-event]
jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Decode cluster.conf
        run: |
          echo "::add-mask::${{ github.event.client_payload.cluster_conf_encoded }}"
          echo "${{ github.event.client_payload.cluster_conf_encoded }}" | base64 -d >> cluster.conf
          cat cluster.conf
